---

- name: Docker Yum Repository (RedHat)
  copy:
    dest: "/etc/yum.repos.d/docker.repo"
    content: "{{docker_repository}}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Docker package (RedHat)
  yum:
    state: present
    name: "{{docker_packages}}"
    update_cache: yes

# vi:ts=2:sw=2:et:ft=yaml
