---

- include: install/Debian.yml
  when: ansible_os_family == 'Debian'

- include: install/RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Docker Python Packages
  pip:
    name: "{{docker_pip_packages}}"
    state: present

# vi:ts=2:sw=2:et:ft=yaml
